### ISSUE TITLE
Should this work on PRs raised from forks?

### ISSUE THREAD

**Issue by andrzejnovak** [peter-evans/create-or-update-comment#42]
I tried to use this instead of the default GHA, because token takes the PAT token. So that I can run an action on a PR from fork, but I get the following message:
```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
##[error]Bad credentials
```
Is this expected behaviour or should it work?

**Comment by peter-evans** [comment]
Hi @andrzejnovak 

Unfortunately, this is expected due to restrictions put in place by GitHub Actions on PRs from forks. I've written a bit about the restrictions [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#restrictions-on-forked-repositories). Although it is referring to a different action, the same applies here. When the workflow runs for a pull request triggered by a fork, it doesn't have access to your PAT in secrets.

Please allow me to correct the title of this issue slightly. The restrictions only apply to PRs raised from forks.

**Comment by andrzejnovak** [comment]
Thanks for clarifying

**Comment by per1234** [comment]
@peter-evans I recommend adding a note to the readme to make this limitation clear.

**Comment by peter-evans** [comment]
Added a note to the readme, but unfortunately this is very common GitHub Actions workflow "gotcha" that is in no way specific to this action. It applies to any action that needs write access to GitHub resources.

I'll close this now, since there is a note in the readme.

**Comment by peter-evans** [comment]
A couple of [new updates](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) have been announced that could help here.

- If your repository is private, you can now [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks.

- If your repository is public, there is a new [`pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) event that is not subject to any token restrictions. I recommend using this event to comment on pull requests.

**Comment by andrzejnovak** [comment]
@peter-evans Indeed. I've complained successfully :D https://github.community/t/inconsistent-on-issue-behaviour/117189/16
