### ISSUE TITLE
Feature Request: Delete Comment

### ISSUE THREAD

**Issue by DanielHabenicht** [peter-evans/create-or-update-comment#63]
I am using this action for displaying informative comments. It would be great to remove the comment to avoid clutter as soon as the issue is resolved.

Would that be something to add to your action?

**Comment by peter-evans** [comment]
Hi @DanielHabenicht 

I don't think comment deletion is in scope for this action, and creating a separate "delete-comment" action is probably overkill because it can be quite easily done using the [github-script](https://github.com/actions/github-script) action. Something like the following snippet: 

```
      - name: Delete comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.fc.outputs.comment-id }},
            })
```

**Comment by DanielHabenicht** [comment]
Ok, thanks for the snippet!
